version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-username/cotacao-dolar:latest
    container_name: cotacao-dolar
    environment:
      - FLASK_APP=api/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: gunicorn --bind 0.0.0.0:8000 api.app:app
