version: '3.8'

services:
  app:
    build: .
    image: cotacao-dolar:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=api/app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: ["flask", "run"]
